### ISSUE TITLE
[universal-redux] Router doesn't accept query params 

### ISSUE THREAD

**Issue by kybarg** [diegohaz/arc#134] opened 2017-02-25 16:26 UTC
This happens if I reload current page if I navigate in loaded application, problem doesn't appear.
What I see in console:
```
console.log(location)
console.log(renderProps.location)
```
```
admin/categories?_limit=100
{ pathname: 'admin/categories',
   search: '',
   hash: '',
   state: undefined,
   action: 'POP',
   key: '859a8w',
   basename: '/',
   query: {} }
 GET /admin/categories?_limit=100 200 223.067 ms - -
```

**Comment by diegohaz** [comment] 2017-02-27 11:56
@kybarg I couldn't reproduce it. `location` and `renderProps.location` have the same value (with qureystring). Could you provide steps to reproduce it (or a repo)? 

Also, does it happen on development (`localhost`)?

**Comment by diegohaz** [comment] 2017-02-27 13:30
Closing (https://github.com/diegohaz/arc/pull/143#issuecomment-282711197)

**Closed by diegohaz** 2017-02-27 13:30 UTC
