### ISSUE TITLE
[universal-redux] Double post list request

### ISSUE THREAD

**Issue by mrsteele** [diegohaz/arc#197] opened 2017-03-29 18:49 UTC
Is it just me, or is the post list request happening twice when you go to the sample page with the list of posts.

I found the issue was here: https://github.com/diegohaz/arc/blob/universal-redux/src/containers/PostList.js#L21

If you first check that the list has already been loaded, there is no need to load this again right?

```javascript
componentDidMount() {
  const { list, loading, request } = this.props
  if (!loading && !list) {
    request()
  }
}
```

Just wanted to raise this and see if anyone else is seeing that as well, I have customized my stack a little bit so it may just be me.

**Comment by diegohaz** [comment] 2017-03-29 19:45
Well, something like that actually happens. It doesn't really fetch "twice", but once on server and once on client (per component mount).

We can't use that verification you suggested because we want to refresh the list every time it mounts (which is every time the user switches to that page).

The problem is that we currently have no way to see if the request was already made by the server.

Server fetches the list here:
https://github.com/diegohaz/arc/blob/c7b54040db3398b214c335c57d84573574f52651/src/containers/SamplePage.js#L16-L20
```js
  static get({ store }) {
    return new Promise((resolve, reject) => {
      store.dispatch(postListReadRequest({ _limit: 15 }, resolve, reject))
    })
  }
```

And the client do that on `componentDidMount` (it isn't called on server).

See #190 and https://github.com/reactGo/reactGo/blob/cf5d76e30d0cb94acade147f60a250470ac9d7f1/app/client.jsx#L23-L27

**Comment by diegohaz** [comment] 2017-03-29 19:48
I'll close this in favor to #190 

The solution we find there will probably fix this as well.

**Closed by diegohaz** 2017-03-29 19:48 UTC

**Comment by mrsteele** [comment] 2017-03-29 21:16
@diegohaz okay. Thanks for the mention. Yeah it just seemed like there was room for optimizing. I'll read over there and see if I can help at all.
